<!--
Generated by: x_legatus_scriba_machina_x.factory
Source: C:/x_runner_x/x_legatus_scriba_machina_x/factory/templates/make_graphviz/examples/rca_payloads.md.tmpl
Commit: 4e07fcfefabcc513efac18af3d225dbd8b910cd3
Rendered: 2025-12-17T07:24:52+00:00
-->
# RCA Payload Gallery

Use these payloads with `x_make_graphviz_x.examples.rca_tool` to render diagrams and markdown evidence. Each scenario ships a ready JSON file plus recommended output directories.

| Payload | JSON | Suggested command |
| --- | --- | --- |
| Switcharoo Digest Regression | `x_make_graphviz_x/examples/switcharoo_rca.json` | `py -3 -m x_make_graphviz_x.examples.rca_tool --input x_make_graphviz_x/examples/switcharoo_rca.json --output-dir "x_0_make_all_x/Change Control/0.20.15/evidence/graphviz_rca/images" --subdir switcharoo-ishikawa --dot-binary "C:\Program Files\Graphviz\bin\dot.exe" --markdown-path "x_0_make_all_x/Change Control/0.20.15/evidence/graphviz_rca/switcharoo_rca.md"` |
| Telemetry Vector Drift | `x_make_graphviz_x/examples/telemetry_vector_rca.json` | `py -3 -m x_make_graphviz_x.examples.rca_tool --input x_make_graphviz_x/examples/telemetry_vector_rca.json --output-dir "x_0_make_all_x/Change Control/0.20.15/evidence/graphviz_rca/images" --subdir telemetry-vector --dot-binary "C:\Program Files\Graphviz\bin\dot.exe" --markdown-path "x_0_make_all_x/Change Control/0.20.15/evidence/graphviz_rca/telemetry_vector_rca.md"` |
| Cache Hygiene Regression | `x_make_graphviz_x/examples/cache_hygiene_rca.json` | `py -3 -m x_make_graphviz_x.examples.rca_tool --input x_make_graphviz_x/examples/cache_hygiene_rca.json --output-dir "x_0_make_all_x/Change Control/0.20.15/evidence/graphviz_rca/images" --subdir cache-hygiene --dot-binary "C:\Program Files\Graphviz\bin\dot.exe" --markdown-path "x_0_make_all_x/Change Control/0.20.15/evidence/graphviz_rca/cache_hygiene_rca.md"` |

> Tip: set `PYTHONPATH=c:\x_runner_x` (or export equivalent) before running so the builder imports resolve cleanly. When `--output-dir` is omitted the CLI now auto-targets the latest Change Control evidence tree (override with `MAKE_GRAPHVIZ_EVIDENCE_ROOT`).
